inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - '**/helpers/dry_crud/**/*.rb'
    - '**/helpers/actions_helper*.rb'
    - '**/helpers/form_helper*.rb'
    - '**/helpers/format_helper*.rb'
    - '**/helpers/i18n_helper*.rb'
    - '**/helpers/table_helper*.rb'
    - '**/helpers/utility_helper*.rb'
    - app/controllers/dry_crud/*.rb
    - app/controllers/crud_controller.rb
    - node_modules/**/*
    - spec/support/crud_*.rb
    - spec/controllers/crud_test_models_controller_spec.rb
    - vendor/**/*
    - stack/**/*
  DisplayCopNames: true

Lint/UnusedMethodArgument:
  Exclude:
    - app/inputs/*array_input.rb

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - db/migrate/*.rb
    - app/decorators/*_decorator.rb
    - app/controllers/events_controller.rb
    - app/controllers/reservations_controller.rb
    - app/inputs/array_input.rb
    - app/models/event.rb
    - app/lib/breadcrumb_builder.rb

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - app/views/api/v1/events/list.json.jbuilder
    - lib/tasks/*.rake
    - spec/**/*_spec.rb

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - app/models/reservation.rb
    - app/controllers/reservations_controller.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - app/controllers/reservations_controller.rb

Metrics/LineLength:
  Max: 90
  Enabled: true
  AllowHeredoc: true
  AllowURI: true
  Exclude:
    - Gemfile
    - config/**/*
    - db/**/*
    - lib/tasks/dbdata.rake
    - spec/*_helper.rb
    - app/controllers/events_controller.rb
    - app/controllers/reservations_controller.rb
    - app/lib/breadcrumb_builder.rb
    - app/action_view/helpers/sanitize_helper.rb

Metrics/MethodLength:
  Max: 15
  Enabled: true
  Exclude:
    - app/schemas/*
    - db/**/*
    - spec/*_helper.rb
    - app/controllers/events_controller.rb
    - app/controllers/reservations_controller.rb
    - app/decorators/*.rb

Metrics/PerceivedComplexity:
  Exclude:
    - app/controllers/reservations_controller.rb

Rails:
  Enabled: true

Rails/OutputSafety:
  Exclude:
    - app/helpers/datatable_helper.rb

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Exclude:
    - app/controllers/events_controller.rb

Style/ModuleFunction:
  Enabled: false
