AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/**/*
    - config/boot.rb
    - config/**/*
    - db/schema.rb
    - node_modules/**/*
    - script/**/*
    - tmp/**/*
    - vendor/**/*
    - Rakefile
    - Gemfile
    - '**/helpers/dry_crud/**/*.rb'
    - '**/helpers/actions_helper*.rb'
    - '**/helpers/form_helper*.rb'
    - '**/helpers/format_helper*.rb'
    - '**/helpers/i18n_helper*.rb'
    - '**/helpers/table_helper*.rb'
    - '**/helpers/utility_helper*.rb'
    - app/controllers/dry_crud/*.rb
    - app/controllers/crud_controller.rb
    - spec/support/crud_*.rb
    - spec/controllers/crud_test_models_controller_spec.rb
  DisplayCopNames: true

Lint/UnusedMethodArgument:
  Exclude:
    - app/inputs/*array_input.rb

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - db/migrate/*.rb
    - app/decorators/*_decorator.rb
    - app/controllers/reservations_controller.rb
    - app/inputs/array_input.rb
    - app/models/event.rb
    - app/lib/breadcrumb_builder.rb

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - app/views/api/v1/events/list.json.jbuilder
    - lib/tasks/*.rake
    - spec/**/*_spec.rb

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - app/models/reservation.rb

Metrics/LineLength:
  Max: 90
  Enabled: true
  Exclude:
    - db/**/*
    - lib/tasks/dbdata.rake
    - spec/*_helper.rb
    - app/controllers/reservations_controller.rb
    - app/lib/breadcrumb_builder.rb
    - app/action_view/helpers/sanitize_helper.rb

Metrics/MethodLength:
  Max: 15
  Enabled: true
  Exclude:
    - db/**/*
    - spec/*_helper.rb
    - app/controllers/reservations_controller.rb
    - app/decorators/*.rb

Rails:
  Enabled: true

Rails/Date:
  Enabled: false

Rails/InverseOf:
  Exclude:
    - app/models/event.rb
    - app/models/team.rb

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/reservations_controller.rb

Rails/OutputSafety:
  Exclude:
    - app/helpers/datatable_helper.rb

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false
