version: '3'
services:
  db:
    image: postgres:9.6.6-alpine
    volumes:
      - './stack/docker/postgres:/docker-entrypoint-initdb.d/'
    environment:
      - DB_NAME=cheidelacoriera_production
      - DB_USER=cheidelacoriera
      - DB_PASSWORD=mypassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --silent --password=mypassword"]
      interval: 10s
      timeout: 10s

  web:
    image: cheidelacoriera:latest
    environment:
      - SERVICE_NAME=web
      - CHEIDELACORIERA_DATABASE_PASSWORD=mypassword
      - RUN_DB_MIGRATE=true
      - DATABASE_URL=postgresql://cheidelacoriera:mypassword@db/cheidelacoriera_production
      # - DATABASE_URL="postgres://cheidelacoriera:mypassword@db:5432/cheidelacoriera_production"
    ports:
      - "3000:3000"
    depends_on:
      - db
